getConfig: >
  SELECT config
  FROM networks
  WHERE id = :networkId;

updateConfig: >
  UPDATE networks SET config = to_jsonb(:config::jsonb) WHERE id = :networkId;

createEntityTable: >
  CREATE TABLE ${table}
    (
      id SERIAL PRIMARY KEY,
      local_identifier TEXT NOT NULL,
      expedition_id INT NOT NULL REFERENCES expeditions (id) ON DELETE CASCADE,
      data JSONB NOT NULL,
      tsv TSVECTOR,
      created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

  CREATE TRIGGER tsvector_update BEFORE INSERT OR UPDATE ON ${table} FOR EACH ROW EXECUTE PROCEDURE entity_tsv_trigger();
  CREATE TRIGGER update_modtime BEFORE UPDATE ON ${table} FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
  CREATE TRIGGER set_createdtime BEFORE INSERT ON ${table} FOR EACH ROW EXECUTE PROCEDURE set_created_column();
  CREATE TRIGGER entity_audit AFTER INSERT OR DELETE OR UPDATE ON ${table} FOR EACH ROW EXECUTE PROCEDURE entity_history();

  CREATE INDEX idx_network_${networkId}_${conceptAlias}_data ON ${table} USING GIN (data);
  CREATE INDEX idx_network_${networkId}_${conceptAlias}_tsv ON ${table} USING GIN (tsv);
  ALTER TABLE ${table}
      ADD CONSTRAINT idx_network_${networkId}_${conceptAlias}_local_identifier_expedition_id UNIQUE (local_identifier, expedition_id);

createChildEntityTable: >
  ALTER TABLE ${table}
      ADD COLUMN parent_identifier TEXT NOT NULL;
  ALTER TABLE ${table}
      ADD CONSTRAINT network_${networkId}_${conceptAlias}_parent_fkey
      FOREIGN KEY (parent_identifier, expedition_id)
      REFERENCES ${parentTable} (local_identifier, expedition_id) ON DELETE CASCADE;
  CREATE INDEX idx_network_${networkId}_${conceptAlias}_parent_identifier_expedition_id ON ${table} (parent_identifier, expedition_id);

createNetworkSchema: >
  CREATE SCHEMA network_${networkId};

  CREATE TABLE network_${networkId}.audit_table
  (
    event_id bigserial primary key,
    table_name text not null, -- table the change was made to
    user_name text, -- user who made the change
    ts TIMESTAMP WITH TIME ZONE NOT NULL, -- timestamp the change happened
    action TEXT NOT NULL CHECK (action IN ('I','D','U', 'T')), -- INSERT, DELETE, UPDATE, or TRUNCATE
    row_data jsonb, -- For INSERT this is the new row values. For DELETE and UPDATE it is the old row values.
    changed_fields jsonb -- Null except UPDATE events. This is the result of jsonb_diff_val(NEW data, OLD data)
  );