getConfig: >
  SELECT config
  FROM projects
  WHERE id = :projectId;

updateConfig: >
  UPDATE projects SET config = to_jsonb(:config::jsonb) WHERE id = :projectId;

createEntityTable: >
  CREATE TABLE ${table}
    (
      id SERIAL PRIMARY KEY,
      local_identifier TEXT NOT NULL,
      expedition_id INT NOT NULL REFERENCES expeditions (id) ON DELETE CASCADE,
      data JSONB NOT NULL,
      tsv TSVECTOR,
      created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

  CREATE TRIGGER tsvector_update BEFORE INSERT OR UPDATE ON ${table} FOR EACH ROW EXECUTE PROCEDURE entity_tsv_trigger();
  CREATE TRIGGER update_modtime BEFORE UPDATE ON ${table} FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
  CREATE TRIGGER set_createdtime BEFORE INSERT ON ${table} FOR EACH ROW EXECUTE PROCEDURE set_created_column();
  CREATE TRIGGER entity_audit AFTER INSERT OR DELETE OR UPDATE ON ${table} FOR EACH ROW EXECUTE PROCEDURE entity_history();

  CREATE INDEX idx_project_${projectId}_${conceptAlias}_data ON ${table} USING GIN (data);
  CREATE INDEX idx_project_${projectId}_${conceptAlias}_tsv ON ${table} USING GIN (tsv);
  ALTER TABLE ${table}
      ADD CONSTRAINT idx_project_${projectId}_local_identifier_expedition_id UNIQUE (local_identifier, expedition_id);

createChildEntityTable: >
  ALTER TABLE ${table}
      ADD COLUMN parent_identifier TEXT NOT NULL;
  ALTER TABLE ${table}
      ADD CONSTRAINT project_${projectId}_${conceptAlias}_parent_fkey
      FOREIGN KEY (parent_identifier, expedition_id)
      REFERENCES ${parentTable} (local_identifier, expedition_id);
  ALTER TABLE ${table}
      DROP CONSTRAINT idx_project_${projectId}_local_identifier_expedition_id;
  ALTER TABLE ${table}
      ADD CONSTRAINT idx_project_${projectId}_parent_identifier_local_identifier_expedition_id UNIQUE (parent_identifier, local_identifier, expedition_id);

createProjectSchema: >
  CREATE SCHEMA project_${projectId};

  CREATE TABLE project_${projectId}.audit_table
  (
    event_id bigserial primary key,
    table_name text not null, -- table the change was made to
    user_name text, -- user who made the change
    ts TIMESTAMP WITH TIME ZONE NOT NULL, -- timestamp the change happened
    action TEXT NOT NULL CHECK (action IN ('I','D','U', 'T')), -- INSERT, DELETE, UPDATE, or TRUNCATE
    row_data jsonb, -- For INSERT this is the new row values. For DELETE and UPDATE it is the old row values.
    changed_fields jsonb -- Null except UPDATE events. This is the result of jsonb_diff_val(NEW data, OLD data)
  );