package biocode.fims.fimsExceptions.errorCodes;

/**
 * @author RJ Ewing
 */
public enum QueryCode implements ErrorCode {
    NO_RESOURCES, INVALID_TYPE, INVALID_QUERY, UNKNOWN_COLUMN, UNKNOWN_ENTITY, UNRELATED_ENTITIES, UNSUPPORTED_QUERY, UNEXPECTED_RESULT, MISSING_RECORD, INVALID_JOIN, UNKNOWN_FILTER
}
